# Starter pipeline
trigger:
 - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: ecr1


steps:
  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'session2'
      regionName: 'us-east-1'
      imageSource: 'imagename'
      repositoryName: 'ecr/ecr1' 
  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'session2'
      regionName: 'us-east-1'
      imageSource: 'imagename'
      sourceImageName: 'image1'
      repositoryName: 'ecr/ecr1'
      PushTag: $(Build.BuildId)
      

  - task: Docker@2
    inputs:
      containerRegistry: 'webamazon'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'session2'
      regionName: 'us-east-1'
      imageSource: 'imagename'
      sourceImageName: 'image1'
      repositoryName: 'ecr/ecr1'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

 

